### PR TITLE
FTSOv2 and Randomv2 examples

### PR DESCRIPTION
**Pull request by AmadiaFlare**
Purpose: This PR adds examples for FTSOv2 and RandomInterfacev2

### CODE REVIEW

**Comment by dineshpinto** [comment]
Hi, please make sure that all checks pass before opening a PR for review, otherwise mark it as draft.

```
  [cause]: Error: Can't process doc metadata for doc at path path=/home/runner/work/developer-hub/developer-hub/docs/ftso/guides/randomnumber-v2-examples.mdx in version name=current
````

**Comment by dineshpinto** [comment]
Additional changes that need to be made:

1. Full code snippets should not be defined in a `.mdx` file, they should be loaded using the raw loader from the `developer-hub/examples` folder, see other guides on how this is done:  https://github.com/flare-foundation/developer-hub/blob/f0ffe328b5256500378c88eda572bac10fb2fc1f/docs/ftso/guides/change-quote-feed.mdx?plain=1#L21
2. When a full Solidity code snippet is presented, it should include a "Open in Remix" button that loads the file from this path: https://github.com/flare-foundation/developer-hub/blob/f0ffe328b5256500378c88eda572bac10fb2fc1f/docs/ftso/guides/change-quote-feed.mdx?plain=1#L31
3. RandomNumberV2 examples should be added to the `Use secure random onchain` section of the Secure Random guide: https://github.com/flare-foundation/developer-hub/blob/f0ffe328b5256500378c88eda572bac10fb2fc1f/docs/network/guides/secure-random-numbers.mdx?plain=1#L86
4. The examples for FTSOv2 are good, but it likely does not belong under guides. Leave it as is for now, once the PR is ready I will rearrange this

**Comment by AmadiaFlare** [comment]
@dineshpinto  Made the changes but not sure what the problem is with `RandomNumberV2` reference error not building on the PR when it is locally.

**Comment by dineshpinto** [comment]
@AmadiaFlare you are using RandomNumberV2 without importing it:

https://github.com/flare-foundation/developer-hub/blob/832f55a46d33337a9809041756031df060e1cedf/docs/ftso/guides/ftsov2-examples.mdx?plain=1#L47

**Comment by dineshpinto** [comment]
@AmadiaFlare, is this ready for review?

**Comment by AmadiaFlare** [comment]
Yes - this is ready for review.

**Comment by dineshpinto** [comment]
@AmadiaFlare thanks, looks good. I have moved the code examples into the solidity reference for `FtsoV2Interface`. One thing, I see it's missing a code example for [getFeedIndex](https://dev.flare.network/ftso/solidity-reference/FtsoV2Interface#getfeedindex) i.e. converting from feed ID to feed index.

**Pull request merged**
